---
title: "Week 9"
author: "Emily Palmer"
date: "11/23/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
devtools::load_all()
```

## Test functions are working 

### Test the movable leaves work 
```{r}
param <- get_gingko_params(init_location = "origin")

leaf <- get_gingko_params(init_location = "origin") %>% 
  grow_leaf()

# One leaf
get_gingko_params(init_location = "origin") %>% 
  grow_leaf() %>% 
  rake_leaves() %>% 
  plot_leaves()

# many leaves 
get_gingko_params(init_location = "origin") %>% 
  spread_leaves() %>% 
  plot_leaves()

```

### Test the initially randomly placed and rotated leaves work

```{r}
# one leaf
param <- get_gingko_params(init_location = "random")

get_gingko_params(init_location = "random") %>%
  grow_leaf() %>% 
  rake_leaves() %>%
  plot_leaves()

# multiple leaves
get_gingko_params() %>% 
  create_leaf_pile() %>% 
  plot_leaves()

initialize <- tibble(
    # Choose a random first location, smaller selection for leafs falling
    x0 = sample(1:50,1),
    y0 = sample(1:50,1),
    x1 = x0,
    y1 = y0 + 1,
    angle = sample(-180:180,1), # Random orientation of leaf orientation
    length = 1,       # initial
    iter_n = 1L       # time used for
  )
grow_leaf_layers(initialize, param)
one_branch(partial_leaf = initialize, param = param)


leaf <- get_gingko_params() %>%
  grow_leaf_random()
```




## Play with different parameter values and output plots 


```{r}

```


## Timing test 
